### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by Laban1** [jackymelb/fpingx#1]
Hello,

I just added fpingx to an existing projects (using Carthage).  It builds fine, but when trying to run / link, the app now crashes with:

`dyld: Library not loaded: @rpath/fpingx.framework/fpingx
  Referenced from: /Users/joe/Library/Developer/CoreSimulator/Devices/BF370471-BAF6-4803-B8B7-AFB51A361441/data/Containers/Bundle/Application/FC8736B5-85E1-41AE-A2F9-F75E5D3BAC32/SomeApp.app/SomeApp
  Reason: image not found
(lldb)`

I have been using several other 3rd-party libraries via Carthage for years and never had this issue until now.  It works fine if I remove fpingx.

Xcode version 10.3, Swift 5

Help would be appreciated.

Thanks.

**Comment by Laban1** [comment]
Bump...

**Comment by jzau** [comment]
Hey @Laban1 , did you add it here?

![image](https://user-images.githubusercontent.com/2881736/74798368-bbeb2f00-5321-11ea-88b4-3b98cbfc7bac.png)

**Comment by Laban1** [comment]
Hey @jzau,

Sorry for the looong delay, just saw your response above.  No, I had missed that.  I added that and it works fine now!

Thanks.
